// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/obj_box_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3780589184208434634),
      name: 'ObjBoxModel',
      lastPropertyId: const IdUid(6, 6573432291607823526),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1310267819196018585),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5860542502207965502),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3610286689667985648),
            name: 'surname',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3619432659727868624),
            name: 'birth_date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2905383896344450198),
            name: 'address',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 6573432291607823526),
            name: 'tel',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 3780589184208434634),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ObjBoxModel: EntityDefinition<ObjBoxModel>(
        model: _entities[0],
        toOneRelations: (ObjBoxModel object) => [],
        toManyRelations: (ObjBoxModel object) => {},
        getId: (ObjBoxModel object) => object.id,
        setId: (ObjBoxModel object, int id) {
          object.id = id;
        },
        objectToFB: (ObjBoxModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final surnameOffset = fbb.writeString(object.surname);
          final birth_dateOffset = fbb.writeString(object.birth_date);
          final addressOffset = fbb.writeString(object.address);
          final telOffset = fbb.writeString(object.tel);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, surnameOffset);
          fbb.addOffset(3, birth_dateOffset);
          fbb.addOffset(4, addressOffset);
          fbb.addOffset(5, telOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final surnameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final birth_dateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final telParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = ObjBoxModel(
              id: idParam,
              name: nameParam,
              surname: surnameParam,
              birth_date: birth_dateParam,
              address: addressParam,
              tel: telParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ObjBoxModel] entity fields to define ObjectBox queries.
class ObjBoxModel_ {
  /// see [ObjBoxModel.id]
  static final id =
      QueryIntegerProperty<ObjBoxModel>(_entities[0].properties[0]);

  /// see [ObjBoxModel.name]
  static final name =
      QueryStringProperty<ObjBoxModel>(_entities[0].properties[1]);

  /// see [ObjBoxModel.surname]
  static final surname =
      QueryStringProperty<ObjBoxModel>(_entities[0].properties[2]);

  /// see [ObjBoxModel.birth_date]
  static final birth_date =
      QueryStringProperty<ObjBoxModel>(_entities[0].properties[3]);

  /// see [ObjBoxModel.address]
  static final address =
      QueryStringProperty<ObjBoxModel>(_entities[0].properties[4]);

  /// see [ObjBoxModel.tel]
  static final tel =
      QueryStringProperty<ObjBoxModel>(_entities[0].properties[5]);
}
